// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfM2rorPtElZZsuLxEFAzIdhHfb96ccKQ',
    appId: '1:96597404835:web:3fc6d26adb41229b3e2316',
    messagingSenderId: '96597404835',
    projectId: 'nagarathar-3d13e',
    authDomain: 'nagarathar-3d13e.firebaseapp.com',
    storageBucket: 'nagarathar-3d13e.firebasestorage.app',
    measurementId: 'G-XF6C6TSZT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3VZgkfaaF_dGGijrZd4dQsAs3suvxz1s',
    appId: '1:759670782026:android:bf254f5340276948f18eb3',
    messagingSenderId: '759670782026',
    projectId: 'nagarathar-events',
    storageBucket: 'nagarathar-events.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3mJpiwOLaVMdwF0H_bylkWmaIda-HFWE',
    appId: '1:759670782026:ios:3d7962c5d492ca66f18eb3',
    messagingSenderId: '759670782026',
    projectId: 'nagarathar-events',
    storageBucket: 'nagarathar-events.firebasestorage.app',
    iosBundleId: 'com.skandaSoft.nagaratharApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOCdHBTcwJorHF0aiakAux54R5nSiPi1E',
    appId: '1:96597404835:ios:0511a7904c9cf0b33e2316',
    messagingSenderId: '96597404835',
    projectId: 'nagarathar-3d13e',
    storageBucket: 'nagarathar-3d13e.firebasestorage.app',
    iosBundleId: 'com.skandaSoft.nagaratharApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYd7kR68h2hx5eQMjQN_Im911Bnnt2yNM',
    appId: '1:96597404835:web:fcf163b4167bf8aa3e2316',
    messagingSenderId: '96597404835',
    projectId: 'nagarathar-3d13e',
    authDomain: 'nagarathar-3d13e.firebaseapp.com',
    storageBucket: 'nagarathar-3d13e.firebasestorage.app',
    measurementId: 'G-6XJ0T1L37J',
  );

}